# Generated by Django 6.0.7 on 2026-08-03 20:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('service', '0011_alter_service_acronym'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=120)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(choices=[('NGN', 'NGN — Nigerian Naira'), ('USD', 'USD — US Dollar')], default='NGN', max_length=3)),
                ('method', models.CharField(choices=[('flutterwave', 'Flutterwave (Cards, Bank Transfer, USSD, Mobile Money)'), ('paystack', 'Paystack (Cards, Bank Transfer, USSD)'), ('binance', 'Binance Pay (Crypto)')], max_length=20)),
                ('reference', models.CharField(editable=False, max_length=100, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('gateway_ref', models.CharField(blank=True, max_length=200, null=True)),
                ('gateway_response', models.TextField(blank=True, null=True)),
                ('paid_date', models.DateTimeField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='service.service')),
            ],
            options={
                'ordering': ('-created_date',),
            },
        ),
    ]
