# Generated by Django 5.2.8 on 2025-12-09 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='socials',
            options={'verbose_name': 'socials', 'verbose_name_plural': 'socials'},
        ),
    ]
