# Generated by Django 5.2.8 on 2025-12-15 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_alter_socials_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactmessage',
            name='intro_text',
        ),
        migrations.RemoveField(
            model_name='contactmessage',
            name='job_title',
        ),
        migrations.RemoveField(
            model_name='contactmessage',
            name='others',
        ),
    ]
