# Generated by Django 5.2.8 on 2025-12-18 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_remove_contactmessage_intro_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmessage',
            name='channel',
            field=models.CharField(choices=[(0, 'How did you find us?'), ('Facebook', 'Facebook'), ('Instagram', 'Instagram'), ('LinkedIn', 'LinkedIn'), ('Threads', 'Threads'), ('Google', 'Google'), ('Youtube', 'Youtube'), ('Tiktok', 'Tiktok'), ('GitHub', 'GitHub'), ('Twitter', 'Twitter'), ('Referral', 'Referral'), ('Telegram', 'Telegram'), ('WhatsApp', 'WhatsApp'), ('Pinterest', 'Pinterest'), ('Others', 'Others')], default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
    ]
