# Generated by Django 6.0.7 on 2026-08-03 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_alter_contactmessage_channel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='referral',
            field=models.CharField(blank=True, help_text='Referral source — e.g. LinkedIn, WhatsApp, or the name of the person who referred them.', max_length=200, null=True),
        ),
    ]
