# Generated by Django 6.0.7 on 2026-08-03 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0005_contactmessage_referral'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('source', models.CharField(blank=True, max_length=100, null=True)),
                ('subscribed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Newsletter Subscriber',
                'verbose_name_plural': 'Newsletter Subscribers',
                'ordering': ('-subscribed_at',),
            },
        ),
        migrations.AddField(
            model_name='socials',
            name='medium',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='socials',
            name='substack',
            field=models.URLField(blank=True, null=True),
        ),
    ]
