# Generated by Django 6.0.7 on 2026-08-04 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=30, null=True)),
                ('topic', models.CharField(blank=True, max_length=100, null=True)),
                ('message', models.TextField(max_length=1000)),
                ('channel', models.CharField(choices=[('chatbot', 'Website Chatbot'), ('site', 'Website'), ('whatsapp', 'WhatsApp'), ('email', 'Email')], default='chatbot', max_length=20)),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('resolved', 'Resolved')], default='new', max_length=20)),
                ('notified', models.BooleanField(default=False, help_text='Whether the owner was alerted (WhatsApp/SMS/email).')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-created_date',),
            },
        ),
    ]
