# Generated by Django 5.2.8 on 2025-12-14 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_service_intro_text_alter_service_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='intro_text',
        ),
    ]
