# Generated by Django 5.2.8 on 2025-12-23 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_alter_service_name_alter_service_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='acronym',
            field=models.CharField(blank=True, editable=False, max_length=20),
        ),
    ]
