# Generated by Django 5.2.8 on 2025-12-24 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0006_service_acronym'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='acronym',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
