# Generated by Django 5.2.8 on 2025-12-24 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0007_alter_service_acronym'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='acronym',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
