"""
Django settings for KingGreatmanSpirit project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from decouple import config
from decouple import Csv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=False, cast=bool)

ALLOWED_HOSTS = config('ALLOWED_HOSTS', cast=Csv())

# Read CSRF trusted origins from .env and split them into a list
CSRF_TRUSTED_ORIGINS = config('CSRF_TRUSTED_ORIGINS', cast=Csv())

# Canonical site URL used in emails, sitemaps and notifications
SITE_URL = config('SITE_URL', default='https://kinggreatmanspirit.com').rstrip('/')

# Google Search Console site verification token (paste from GSC)
GOOGLE_SITE_VERIFICATION = config('GOOGLE_SITE_VERIFICATION', default='')

# Google Analytics 4 measurement id (e.g. G-XXXXXXXXXX)
GA4_MEASUREMENT_ID = config('GA4_MEASUREMENT_ID', default='')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sitemaps',

    # Django Apps
    'smart_selects',
    'about',
    'resume',
    'portfolio',
    'service',
    'contact',
    'accounts',
    'payments',
    'dashboard',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'KingGreatmanSpirit.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],  # your templates directory
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                # Your About context processor
                'about.context_processors.about_links',
                'portfolio.context_processors.portfolio_links',
                'contact.context_processors.socials_links',
                'service.context_processors.menu_links',
                'dashboard.context_processors.dashboard_globals',
                'KingGreatmanSpirit.context_processors.site_config',
            ],
        },
    },
]

WSGI_APPLICATION = 'KingGreatmanSpirit.wsgi.application'

AUTH_USER_MODEL = 'accounts.Account'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Automatic: PostgreSQL when DB_ENGINE is set (Docker / VPS), SQLite otherwise
# (local development with no extra setup). Set DB_ENGINE, DB_NAME, DB_USER,
# DB_PASSWORD, DB_HOST, DB_PORT in .env for PostgreSQL.
DB_ENGINE = config('DB_ENGINE', default='')

if DB_ENGINE == 'django.db.backends.postgresql':
    DATABASES = {
        'default': {
            'ENGINE': DB_ENGINE,
            'NAME': config('DB_NAME', default='kgs_db'),
            'USER': config('DB_USER', default='kgs_user'),
            'PASSWORD': config('DB_PASSWORD', default='kgs_password'),
            'HOST': config('DB_HOST', default='db'),
            'PORT': config('DB_PORT', default='5432'),
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': str(BASE_DIR / 'db.sqlite3'),
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'static'  # This is where collectstatic will gather static files

STATICFILES_DIRS = [
    BASE_DIR / 'KingGreatmanSpirit' / 'static',  
]

# Media files configuration
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'  # Absolute path to the media directory in your project

# For files
FILE_UPLOAD_PERMISSIONS = 0o755 #or whatever fits to your needs
# For directories
FILE_UPLOAD_DIRECTORY_PERMISSIONS = 0o755

USE_DJANGO_JQUERY = True

# Production hardening (auto-enabled when DEBUG=False)
if not DEBUG:
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_REFERRER_POLICY = 'strict-origin-when-cross-origin'

# Message tags
from django.contrib.messages import constants as messages
MESSAGE_TAGS = {
    messages.ERROR: 'danger',
}

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# SMTP configuration
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = config('EMAIL_HOST')
EMAIL_PORT = config('EMAIL_PORT', default=587)
EMAIL_HOST_USER = config('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD')
EMAIL_USE_TLS = config('EMAIL_USE_TLS', default=False, cast=bool)
EMAIL_USE_SSL = config('EMAIL_USE_SSL', default=False, cast=bool)
DEFAULT_FROM_EMAIL = config('DEFAULT_FROM_EMAIL', default='King Greatman Spirit <kinggreatmanspirit@gmail.com>')

# =============================================================
# PAYMENT GATEWAYS
# Flutterwave:  https://dashboard.flutterwave.com
# Paystack:     https://dashboard.paystack.com
# Binance Pay:  https://merchant.binance.com
# Leave keys empty to run in "manual verification" mode.
# =============================================================
FLUTTERWAVE_PUBLIC_KEY = config('FLUTTERWAVE_PUBLIC_KEY', default='')
FLUTTERWAVE_SECRET_KEY = config('FLUTTERWAVE_SECRET_KEY', default='')
FLUTTERWAVE_WEBHOOK_SECRET = config('FLUTTERWAVE_WEBHOOK_SECRET', default='')

PAYSTACK_PUBLIC_KEY = config('PAYSTACK_PUBLIC_KEY', default='')
PAYSTACK_SECRET_KEY = config('PAYSTACK_SECRET_KEY', default='')

BINANCE_API_KEY = config('BINANCE_API_KEY', default='')
BINANCE_PRIVATE_KEY = config('BINANCE_PRIVATE_KEY', default='')
BINANCE_MERCHANT_ID = config('BINANCE_MERCHANT_ID', default='')
BINANCE_NGN_USDT_RATE = config('BINANCE_NGN_USDT_RATE', default='')
BINANCE_ENABLED = config('BINANCE_ENABLED', default='False') == 'True'
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER

# =============================================================
# LIVE SUPPORT ALERTS (support tickets -> WhatsApp + SMS)
# Get free credentials at https://www.twilio.com
# Leave empty to fall back to email notifications.
# =============================================================
TWILIO_ACCOUNT_SID = config('TWILIO_ACCOUNT_SID', default='')
TWILIO_AUTH_TOKEN = config('TWILIO_AUTH_TOKEN', default='')
TWILIO_WHATSAPP_FROM = config('TWILIO_WHATSAPP_FROM', default='whatsapp:+14155238886')
TWILIO_SMS_FROM = config('TWILIO_SMS_FROM', default='')
SUPPORT_NOTIFY_WHATSAPP_TO = config('SUPPORT_NOTIFY_WHATSAPP_TO', default='whatsapp:+2349014155705')
SUPPORT_NOTIFY_PHONE = config('SUPPORT_NOTIFY_PHONE', default='+2349014155705')
SUPPORT_NOTIFY_EMAIL = config('SUPPORT_NOTIFY_EMAIL', default='spiritpydev@gmail.com')