# Generated by Django 5.2.8 on 2025-12-09 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='intro_text',
        ),
    ]
