# Generated by Django 5.2.8 on 2025-12-09 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_remove_skill_intro_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='statistic',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
