# Generated by Django 5.2.8 on 2025-12-10 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_statistic_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statistic',
            name='name',
        ),
        migrations.AddField(
            model_name='statistic',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='statistic',
            name='icon',
            field=models.CharField(blank=True, help_text='Example: bi bi-emoji-smile', max_length=100, null=True),
        ),
    ]
