# Generated by Django 5.2.8 on 2025-12-04 17:30

import django.db.models.deletion
import smart_selects.db_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('about', '0001_initial'),
        ('portfolio', '0001_initial'),
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='service',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='about', chained_model_field='about', default=None, on_delete=django.db.models.deletion.CASCADE, to='service.service'),
        ),
        migrations.AddField(
            model_name='projectimages',
            name='about',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_images', to='about.about'),
        ),
        migrations.AddField(
            model_name='projectimages',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_images', to='portfolio.project'),
        ),
        migrations.AddField(
            model_name='projectimages',
            name='service',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='about', chained_model_field='about', default=None, on_delete=django.db.models.deletion.CASCADE, to='service.service'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='about',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testimonials', to='about.about'),
        ),
    ]
