# Generated by Django 5.2.8 on 2025-12-23 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='weblink',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
