# Generated by Django 5.2.8 on 2025-12-24 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_testimonial_weblink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectimages',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='projectimages',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
