# Generated by Django 5.2.8 on 2025-12-24 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_alter_projectimages_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectimages',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='projectimages',
            name='modified_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
