# Generated by Django 5.2.8 on 2025-12-24 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_projectimages_created_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='client',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='industry',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
