# Generated by Django 5.2.8 on 2025-12-24 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_project_client_project_industry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_scope',
            field=models.TextField(max_length=1000),
        ),
    ]
