# Generated by Django 5.2.8 on 2025-12-14 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='summary',
            options={'verbose_name': 'summary', 'verbose_name_plural': 'summaries'},
        ),
        migrations.AddField(
            model_name='summary',
            name='resume_desc',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
