# Generated by Django 5.2.8 on 2025-12-14 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_alter_summary_options_summary_resume_desc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='summary',
            name='resume_desc',
        ),
    ]
