# Generated by Django 5.2.8 on 2025-12-14 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0003_remove_summary_resume_desc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='experience',
            old_name='description',
            new_name='desc_four',
        ),
        migrations.AddField(
            model_name='experience',
            name='desc_one',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='desc_three',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='desc_two',
            field=models.TextField(blank=True, null=True),
        ),
    ]
