# Generated by Django 5.2.8 on 2025-12-15 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0004_rename_description_experience_desc_four_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='desc_four',
        ),
    ]
